#!/usr/bin/env python3
"""Render a release-pinned Homebrew Formula for the Muxiva CLI."""

from __future__ import annotations

import argparse
import pathlib
import re


SEMVER = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+(?:[-+][0-9A-Za-z.-]+)?$")
SHA256 = re.compile(r"^[0-9a-f]{64}$")


def checked(value: str, pattern: re.Pattern[str], label: str) -> str:
    if not pattern.fullmatch(value):
        raise SystemExit(f"invalid {label}: {value!r}")
    return value


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", required=True)
    parser.add_argument("--repository", required=True)
    parser.add_argument("--arm64-sha256", required=True)
    parser.add_argument("--x86-64-sha256", required=True)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()

    version = checked(args.version, SEMVER, "version")
    arm64_sha = checked(args.arm64_sha256, SHA256, "ARM64 SHA-256")
    x86_sha = checked(args.x86_64_sha256, SHA256, "x86_64 SHA-256")
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", args.repository):
        raise SystemExit(f"invalid GitHub repository: {args.repository!r}")

    release_root = (
        f"https://github.com/{args.repository}/releases/download/v{version}"
    )
    formula = f'''# Generated by scripts/release/render-homebrew-formula.py. Do not edit.
class Muxiva < Formula
  desc "Real-time multimodal agent runtime and CLI"
  homepage "https://github.com/{args.repository}"
  version "{version}"
  license "Apache-2.0"

  on_arm do
    url "{release_root}/muxiva-v{version}-aarch64-apple-darwin.tar.gz"
    sha256 "{arm64_sha}"
  end

  on_intel do
    url "{release_root}/muxiva-v{version}-x86_64-apple-darwin.tar.gz"
    sha256 "{x86_sha}"
  end

  def install
    bin.install "muxiva"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/muxiva --version")
  end
end
'''
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(formula, encoding="utf-8")
    print(f"rendered {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
