from typing import Any, Callable, List, Literal, Optional, Sequence, Tuple

class MuxivaError(Exception): ...

class Frame:
    @property
    def frame_type(self) -> str: ...
    @property
    def frame_id(self) -> str: ...
    @property
    def timestamp_ns(self) -> int: ...
    @property
    def sequence(self) -> int: ...

class TextFrame(Frame):
    def __init__(self, text: str, *, timestamp_ns: int = ..., sequence: int = ...) -> None: ...
    @property
    def text(self) -> str: ...
    def as_frame(self) -> Frame: ...

class ByteFrame(Frame):
    def __init__(self, data: bytes, *, media_type: Optional[str] = ..., timestamp_ns: int = ..., sequence: int = ...) -> None: ...
    @property
    def data(self) -> bytes: ...
    @property
    def media_type(self) -> Optional[str]: ...
    def as_frame(self) -> Frame: ...

class AudioFrame(Frame):
    def __init__(self, data: bytes, sample_rate_hz: int, channels: int, samples_per_channel: int, *, sample_format_name: str = ..., layout: str = ..., timestamp_ns: int = ..., sequence: int = ...) -> None: ...
    @property
    def data(self) -> bytes: ...
    @property
    def sample_rate_hz(self) -> int: ...
    @property
    def channels(self) -> int: ...
    @property
    def samples_per_channel(self) -> int: ...
    def as_frame(self) -> Frame: ...

class VideoFrame(Frame):
    def __init__(self, data: bytes, width: int, height: int, *, pixel_format: str = ..., strides: Optional[Sequence[int]] = ..., timestamp_ns: int = ..., sequence: int = ...) -> None: ...
    @property
    def data(self) -> bytes: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    def as_frame(self) -> Frame: ...

class SignalFrame(Frame):
    def __init__(self, name: str, payload: str = ..., *, source: str = ..., schema_version: int = ..., timestamp_ns: int = ..., sequence: int = ...) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def payload(self) -> str: ...
    def as_frame(self) -> Frame: ...

class EventFrame(Frame):
    def __init__(self, topic: str, payload: str = ..., *, source: str = ..., schema_version: int = ..., timestamp_ns: int = ..., sequence: int = ...) -> None: ...
    @property
    def topic(self) -> str: ...
    @property
    def payload(self) -> str: ...
    def as_frame(self) -> Frame: ...

class PythonNodeExecutionDomain:
    def __init__(self, node: Any, *, inbox_capacity: int = ..., completion_capacity: int = ..., max_in_flight: int = ..., call_deadline_ms: int = ..., shutdown_deadline_ms: int = ..., ordering: str = ..., isolation: str = ...) -> None: ...
    def prepare(self) -> None: ...
    def process(self, frame: Frame) -> List[Frame]: ...
    def signal(self, signal: SignalFrame) -> None: ...
    def event(self, event: EventFrame) -> None: ...
    def finish(self) -> None: ...
    def abort(self, reason: str) -> None: ...
    def close(self) -> bool: ...
    @property
    def is_closed(self) -> bool: ...

class GraphNodeFactory:
    def __init__(self, node_type: str, constructor: Callable[..., Any], *, version: str = ..., input_port: str = ..., output_port: str = ..., kind: Literal["source", "transform", "sink"] = ..., ports_json: Optional[str] = ..., config_schema_json: str = ..., pass_config: bool = ...) -> None: ...
    @property
    def node_type(self) -> str: ...
    @property
    def version(self) -> str: ...

def run_graph(graph_json: str, factories: Sequence[GraphNodeFactory], *, timeout_ms: int = ...) -> int: ...

class Session:
    @property
    def id(self) -> str: ...
    @property
    def is_closed(self) -> bool: ...
    def close(self) -> bool: ...

class Runtime:
    def session(self) -> Session: ...
    @property
    def is_closed(self) -> bool: ...
    def close(self) -> bool: ...

class EventBus:
    def __init__(self, capacity: int = ...) -> None: ...
    def publish(self, event: EventFrame) -> Tuple[int, int, int]: ...
    def subscribe(self, topic: str, domain: PythonNodeExecutionDomain) -> int: ...
    @property
    def is_closed(self) -> bool: ...
    def close(self) -> bool: ...
