[package]
name = "voxa-ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
libloading.workspace = true
voxa-core = { path = "../voxa-core" }
voxa-graph-json = { path = "../voxa-graph-json" }
voxa-types.workspace = true
