[package]
name = "voxa-node"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]

[dependencies]
napi = { version = "2.16", features = ["napi8", "dyn-symbols"] }
napi-derive = "2.16"
voxa-types = { path = "../voxa-types" }
voxa-core = { path = "../voxa-core" }

[build-dependencies]
napi-build = "2.1"

[profile.release]
lto = true
strip = "symbols"
